name: PR Preview Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare clean branch name
        id: clean
        run: |
          CLEAN="${GITHUB_HEAD_REF//\//-}"
          echo "clean_branch=$CLEAN" >> $GITHUB_OUTPUT

      - name: Create PR Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ğŸ” **Preview is live!**

            ğŸ‘‰ https://othaldo.github.io/stevenschwarz/${{ steps.clean.outputs.clean_branch }}/
